# Generated by Django 3.2.16 on 2022-11-17 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Username', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('AccessLevel', models.CharField(choices=[('A', 'Admin'), ('E', 'Employee'), ('M', 'Manager')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('CarID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1930), django.core.validators.MaxValueValidator(2023)])),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=20)),
                ('miles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500000)])),
                ('color', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('L', 'Lot'), ('D', 'Detail'), ('S', 'Service')], max_length=1)),
                ('DateAdded', models.DateField()),
            ],
        ),
    ]
